#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
menuentry "EFI Shell" {
    chainloader (hd0,gpt1)/shellx64_v2.efi
}

menuentry "Memtest" {
    chainloader (hd0,gpt1)/memtest64.efi
}
